# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wU1UP42ZWbwqZdndgfu9Y3GDdhFcHNkf
"""

import getpass
nutzer={"Alaa":"1998" ,"Abdullah":"1997","Dania":"2003","Tahani":"1993"}
def login(nutzer) :
  i=1
  while True:
   a=input("Geben Sie bitte Ihr Nutzername ")
   b=getpass.getpass("Geben sie bitte Ihr Passwort ")
   if a in nutzer and nutzer[a]==b:
        print("Willkommen in Ihrem Konto")
        break
   else :
        if i == 2:
           print("System gesperrt")
           break
        else:
           print("Zugriff verweigert")
           a=input("Geben Sie bitte nochmal Ihr Nutzername:  ")
           b=getpass.getpass("Geben Sie bitte nochmal Ihr Passwort")
           i+=1
           if a in nutzer and nutzer[a]==b:
             print("Willkommen in Ihrem Konto")
             break
           else:
            if i == 2:
              print("System gesperrt")
              break
n=input("Haben Sie schon ein Konto? (ja/nein)").lower()
if n!="ja" and n!="nein" :
 print("Bitte gib nur 'ja' oder 'nein' ein.")
 n=input("Haben Sie schon ein Konto? (ja/nein)").lower()
while True:
  if n == "ja" :
    login(nutzer)
    break
  else:
    q=input("Möchten Sie ein neues Konto erstellen? (ja/nein) ").lower()
    if q=="ja":
      ä=input("Geben Sie bitte Ihr neues Nutzername ")
      ö=getpass.getpass("Geben Sie bitte Ihr neues Passwort")
      ü=getpass.getpass("Neues Passwort wiederholen")

      if ö!=ü:
        print("Passwort stimmt nicht überein. Registierung fehlgeschlagen. ")
      else:
        nutzer[ä]=ö
        print("Konto erfolgreich erstellen .")
        login(nutzer)
        break